In [2]:
# numpy -> provide support for arrays and matrices , and its operation
!pip install numpy

In [5]:
import numpy as np


# create 1d array using numpy

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
# 2d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3.shape)

(2, 5)


In [8]:
print(arr3)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

6
2
int64
8


In [21]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# add
print('Addition:',arr1+arr2)

# sub
print('Subtraction:',arr1-arr2)
print('Multiply:',arr1*arr2)
print('Division:',arr1/arr2)


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiply: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [27]:
## universal function
arr=np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
# array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
print(arr[0][1])

2


In [33]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [35]:
print(arr[0:2,2:4])

[[3 4]
 [7 8]]


In [38]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [39]:
# modofy array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [44]:
# statistical concept -> normalization
arr=np.array([10,20,30,40,50])

arrMean=np.mean(arr)
arrStandardDeviation=np.std(arr)

print(arrMean)
print(arrStandardDeviation)

print(np.median(arr))

print(np.var(arr))



30.0
14.142135623730951
30.0
200.0


In [53]:
# logical operation 
data=np.array([1,2,3,4,5,6,7,8,9])
print(data>5)
data [(data>5) & (data<=8)]

[False False False False False  True  True  True  True]


array([6, 7, 8])